pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'sksawsdev/appx:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/suanx/java-cicd-on-eks.git', branch: 'main'
            }
        }

        stage('Build & Unit Tests') {
            steps {
                dir('app') {
                    // Run package with tests
                    sh 'mvn clean package'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('app') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                // Wait for SonarQube analysis to finish and check quality gate status
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Login') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'Doc-cred-global', passwordVariable: 'docpass', usernameVariable: 'docusr')]) {
                        sh "echo \"$docpass\" | docker login -u $docusr --password-stdin"
                    }
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh """
                   docker build -t $DOCKER_IMAGE ./app
                   docker push $DOCKER_IMAGE
                """
            }
        }
    }

    post {
        success {
            echo '✅ Build, scan and push completed successfully.'
        }
        failure {
            echo '❌ Pipeline failed.'
        }
    }
}
