pipeline {
    agent any                   

    environment {
        DOCKER_IMAGE = 'sksawsdev/appx:latest'
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/suanx/java-cicd-on-eks.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Docker Login') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'Doc-cred-global', passwordVariable: 'docpass', usernameVariable: 'docusr')]) {
                        sh 'echo $docpass | docker login -u $docusr --password-stdin'
                    }
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh """
                   docker build -t $DOCKER_IMAGE .
                   docker push $DOCKER_IMAGE
                """
            }
        }
    }

    post {
        success {
            echo '✅ Build, scan and push completed successfully.'
        }
        failure {
            echo '❌ Pipeline failed.'
        }
    }
}
